Repository codeit-team2/codeit-team2-be, pull requests merged in 2024-07, with the labels that each got.

#6 애플리케이션 공통 설정 추가 및 프로젝트 기본 설정 수정
  chwizone/settings.gradle
  hobbyzone/.gitignore
  hobbyzone/build.gradle
  hobbyzone/gradle/wrapper/gradle-wrapper.jar
  hobbyzone/gradle/wrapper/gradle-wrapper.properties
  hobbyzone/gradlew
  hobbyzone/gradlew.bat
  hobbyzone/lombok.config
  hobbyzone/settings.gradle
  hobbyzone/src/main/java/com/codeit/hobbyzone/HobbyZoneApplication.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/common/domain/BaseTimeEntity.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/common/domain/Builder.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/common/domain/CreateTimeEntity.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/common/exception/ExceptionStatus.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/common/exception/GlobalControllerAdvice.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/common/exception/dto/BaseExceptionDto.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/common/exception/dto/ParameterExceptionDto.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/config/JpaConfig.java
  hobbyzone/src/main/resources/application-local.yml
  hobbyzone/src/main/resources/application.yml
  hobbyzone/src/main/resources/logback-spring.xml
  hobbyzone/src/test/java/com/codeit/hobbyzone/HobbyZoneApplicationTests.java
  hobbyzone/src/test/java/com/codeit/hobbyzone/common/DatabaseCleanListener.java
  hobbyzone/src/test/java/com/codeit/hobbyzone/common/IntegrationTest.java
Labels: environment, feature, refactor

#12 공통 예외 처리 방식 변경
  hobbyzone/src/main/java/com/codeit/hobbyzone/account/domain/exception/InvalidNicknameException.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/account/domain/exception/InvalidPasswordEncoderException.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/account/domain/exception/InvalidPasswordException.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/auth/application/exception/AlreadyVerifyAccountException.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/auth/application/exception/DuplicateNicknameException.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/auth/application/exception/NotVerifyAccountException.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/auth/application/exception/VerificationFailedException.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/auth/application/exception/VerifyAccountNotFoundException.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/auth/domain/exception/ExpiredVerifyCodeException.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/auth/domain/exception/VerifyFailedException.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/auth/infrastructure/exception/MailSendFailedException.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/common/exception/ExceptionStatus.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/common/exception/GlobalControllerAdvice.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/common/exception/base/account/AccountClientException.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/common/exception/base/account/AccountServerException.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/common/exception/base/auth/SignUpClientException.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/common/exception/base/auth/SignUpServerException.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/common/exception/code/AccountErrorCode.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/common/exception/code/CommonErrorCode.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/common/exception/code/SignUpErrorCode.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/common/exception/translate/AccountExceptionTranslator.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/common/exception/translate/CommonExceptionTranslator.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/common/exception/translate/SignUpExceptionTranslator.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/config/AppConfig.java
  hobbyzone/src/test/java/com/codeit/hobbyzone/auth/presentation/SignUpControllerTest.java
Labels: refactor

#13 회원 인증 관련 기능 구현
  hobbyzone/src/main/java/com/codeit/hobbyzone/account/domain/Account.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/account/presentation/AccountRepository.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/auth/application/AuthService.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/auth/application/BlacklistTokenService.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/auth/application/ValidateAccountService.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/auth/application/dto/response/TokenDto.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/auth/application/exception/PasswordMismatchException.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/auth/application/exception/UnregisteredAccountException.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/auth/config/exception/AccountUnauthorizedException.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/auth/config/interceptor/AuthAccountInfo.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/auth/config/interceptor/AuthInterceptor.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/auth/config/interceptor/AuthStore.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/auth/config/properties/JwtConfigurationProperties.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/auth/config/resolver/AuthAccount.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/auth/config/resolver/AuthAccountInfoArgumentResolver.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/auth/domain/exception/EmptyTokenException.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/auth/domain/token/BlacklistToken.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/auth/domain/token/PrivateClaims.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/auth/domain/token/TokenDecoder.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/auth/domain/token/TokenEncoder.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/auth/domain/token/TokenScheme.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/auth/domain/token/TokenType.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/auth/infrastructure/BlacklistTokenRepository.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/auth/infrastructure/exception/InvalidTokenException.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/auth/infrastructure/mail/GoogleMailSender.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/auth/infrastructure/mail/LocalMailSender.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/auth/infrastructure/token/JwtDecoder.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/auth/infrastructure/token/JwtEncoder.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/auth/presentation/AuthController.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/auth/presentation/dto/request/SignInDto.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/auth/presentation/dto/response/AccessTokenDto.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/auth/presentation/exception/RefreshTokenNotFoundException.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/common/exception/GlobalControllerAdvice.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/common/exception/base/auth/AuthClientException.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/common/exception/base/auth/AuthServerException.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/common/exception/code/AuthErrorCode.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/common/exception/translate/AuthExceptionTranslator.java
  hobbyzone/src/main/java/com/codeit/hobbyzone/config/AppConfig.java
  hobbyzone/src/main/resources/application-local.yml
  hobbyzone/src/test/java/com/codeit/hobbyzone/account/domain/AccountTest.java
  hobbyzone/src/test/java/com/codeit/hobbyzone/auth/application/AuthServiceTest.java
  hobbyzone/src/test/java/com/codeit/hobbyzone/auth/application/BlacklistTokenServiceTest.java
  hobbyzone/src/test/java/com/codeit/hobbyzone/auth/application/ValidateAccountServiceTest.java
  hobbyzone/src/test/java/com/codeit/hobbyzone/auth/domain/token/BlacklistTokenTest.java
  hobbyzone/src/test/java/com/codeit/hobbyzone/auth/infrastructure/token/JwtDecoderTest.java
  hobbyzone/src/test/java/com/codeit/hobbyzone/auth/infrastructure/token/JwtEncoderTest.java
  hobbyzone/src/test/java/com/codeit/hobbyzone/auth/presentation/AuthControllerTest.java
  hobbyzone/src/test/java/com/codeit/hobbyzone/auth/presentation/SignUpControllerTest.java
  hobbyzone/src/test/resources/application.yml
Labels: feature

#16 feat: #15 Https 통신 CORS 에러 해결
  hobbyzone/src/main/java/com/codeit/hobbyzone/config/WebConfig.java
Labels: feature
